name: Deploy to Remote Server

on:
  push:
    branches:
      - hw6

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.BACKDEV }}

      - name: Add remote host to known_hosts
        run: |
          ssh-keyscan -p 23498 5.144.96.120 >> ~/.ssh/known_hosts

      - name: Sync project to server
        run: |
          rsync -avz --delete --exclude=".git" -e "ssh -p 23498" ./ root@5.144.96.120:/root/backdev/

      - name: Deploy with docker-compose
        run: |
          ssh -p 23498 root@5.144.96.120 '
            cd "/root/backdev/БР1.2/Корчагин Вадим/labs/lab4/" &&
            docker-compose down &&
            docker-compose pull &&
            docker-compose up -d --build
          '